In [1]:
from datetime import datetime
from pathlib import Path
import re

import pandas as pd

In [2]:
PROJECT_DIR = Path.cwd().resolve().parents[1] / 'anaconda'

PROCESSED_DIR = PROJECT_DIR / 'data' / 'processed'

In [3]:
INPUT_CSV_PATH = (
    PROCESSED_DIR
    / 'site_01_parsed_cats_20260828.csv'
)

cats_df = pd.read_csv(
    INPUT_CSV_PATH
)

cats_df.head()

,name,breed,detail_url,img_url,gender,age,color,feature,branch
0,홀앙,브리티쉬 먼치킨,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,여아,2개월령,골드바이,왕눈이에 생긴 것 마냥 성격도 순둥이!,왕십리점
1,쨈,브리티쉬 먼치킨,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,남아,2개월령,크림바이,오밀조밀 공주 이목구비지만 멋쟁이 왕자다냥!,잠실점
2,리즈,랙돌,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,여아,2개월령,블루바이,품에 안기는 순간 인형처럼 스르륵 녹아내리는 원조 봉제인형 냥이,잠실점
3,우디,브리티쉬숏헤어,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,남아,2개월령,블루골드,느긋한 발걸음으로 집사 뒤를 묵묵히 쫓아오는 든든한 친구,왕십리점
4,통깨,노르웨이숲,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,여아,2개월령,블루태비앤화이트,NaN,왕십리점

In [4]:
print(cats_df.shape)
print(cats_df.columns.tolist())

cats_df.info()

(1462, 9)
['name', 'breed', 'detail_url', 'img_url', 'gender', 'age', 'color', 'feature', 'branch']
<class 'pandas.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1462 non-null   str
 1   breed       1461 non-null   str
 2   detail_url  1462 non-null   str
 3   img_url     1462 non-null   str
 4   gender      1461 non-null   str
 5   age         1460 non-null   str
 6   color       1460 non-null   str
 7   feature     1457 non-null   str
 8   branch      1417 non-null   str
dtypes: str(9)
memory usage: 102.9 KB

In [5]:
print('gender')
display(
    cats_df['gender']
    .value_counts(dropna=False)
)

print('age')
display(
    cats_df['age']
    .value_counts(dropna=False)
    .head(30)
)

print('breed')
display(
    cats_df['breed']
    .value_counts(dropna=False)
    .head(30)
)

print('color')
display(
    cats_df['color']
    .value_counts(dropna=False)
    .head(30)
)

print('branch')
display(
    cats_df['branch']
    .value_counts(dropna=False)
)

gender

gender
남아          914
여아          504
남아,여아        20
2개월령          4
남아, 여아        3
남아&여아         2
남아/여아         2
2개월           2
여아, 남아        1
골드            1
수             1
남아 여아         1
모비            1
암             1
남자            1
여아/남아         1
여아,남아         1
남아,여아,여아      1
NaN           1
Name: count, dtype: int64

age

age
2개월령     1425
2개월        13
3개월령       10
남아          4
NaN         2
4개월령        1
5개월령        1
2개워령        1
1개월령        1
6개월령        1
2개월량        1
여아          1
남아,여아       1
Name: count, dtype: int64

breed

breed
브리티쉬숏헤어      397
브리티쉬 먼치킨     182
랙돌            93
데본렉스          83
스코티쉬폴드        64
아메리칸숏헤어       55
러시안블루         54
페르시안          49
먼치킨 미뉴엣       47
노르웨이숲         46
샴             43
아비시니안         41
메인쿤           33
뱅갈            31
스핑크스          21
셀커크렉스         20
아메리칸컬         18
먼치킨 래가퍼       18
브리티쉬롱헤어       17
먼치킨           17
먼치킨 킬트        11
싱가푸라          10
노르웨이 숲        10
하이랜드폴드        10
먼치킨 킨카로우      10
먼치킨 램킨         9
터키쉬앙고라         9
노르웨이숲 먼치킨      6
먼치킨 밤비노        6
엑죠틱            5
Name: count, dtype: int64

color

color
블루바이         117
블루           112
화이트           93
골드            89
블루골드          61
브라운태비앤화이트     51
실버태비          47
크림바이          41
실버태비앤화이트      39
씰바이           39
실버클래식태비       37
크림            33
크림앤화이트        33
블루포인트         30
블랙            28
씰포인트          27
블루태비앤화이트      25
브라운태비         24
크림태비          23
레드태비앤화이트      22
블루골드바이        18
토티앤화이트        18
골드태비          17
실버쉐이드         16
크림태비앤화이트      16
레드태비          16
브라운로젯         16
블루태비          14
크림포인트         14
블랙바이          12
Name: count, dtype: int64

branch

branch
왕십리점            822
마포점             453
잠실점             138
NaN              45
왕십리               2
031-657-7024      1
02-2299-0014      1
Name: count, dtype: int64

In [6]:
print(
    'detail_url 중복 수 :',
    cats_df['detail_url']
    .duplicated()
    .sum()
)

print(
    '전체 행 중복 수 :',
    cats_df
    .duplicated()
    .sum()
)

detail_url 중복 수 : 0
전체 행 중복 수 : 0

In [7]:
def normalize_age(value):
    match = re.search(r'\d+', str(value))

    if match:
        return int(match.group())

    return None

In [8]:
TEXT_COLUMNS = [
    'name',
    'breed',
    'gender',
    'color',
    'feature',
    'branch',
]

for column in TEXT_COLUMNS:
    cats_df[column] = (
        cats_df[column]
        .astype(str)
        .str.strip()
    )

In [9]:
GENDER_MAP = {
    '남아': 'M',
    '여아': 'F',
}

cats_df['gender'] = (
    cats_df['gender']
    .map(GENDER_MAP)
)

In [10]:
cats_df['gender'].value_counts(dropna=False)

gender
M      914
F      504
NaN     44
Name: count, dtype: int64

In [11]:
sorted(
    cats_df['breed']
    .dropna()
    .unique()
)

['네바마스커레이드',
 '네벨룽',
 '노르웨이 숲',
 '노르웨이숲',
 '노르웨이숲 먼치킨',
 '데본렉스',
 '랙돌',
 '러시안블루',
 '렉돌',
 '먼치',
 '먼치킨',
 '먼치킨 드월프',
 '먼치킨 래가퍼',
 '먼치킨 램킨',
 '먼치킨 미뉴엣',
 '먼치킨 미뉴엣 (롱)',
 '먼치킨 민스킨',
 '먼치킨 밤비노',
 '먼치킨 엑죠틱',
 '먼치킨 킨카로우',
 '먼치킨 킬트',
 '메인쿤',
 '발리니즈',
 '뱅갈',
 '벵갈',
 '브리티쉬 먼처킨',
 '브리티쉬 먼치킨',
 '브리티쉬롱헤어',
 '브리티쉬먼치킨',
 '브리티쉬숏헤어',
 '브리티쉿쇼헤어',
 '샴',
 '샴 먼치킨',
 '셀커크랙스',
 '셀커크렉스',
 '스코티쉬 스트레이트',
 '스코티쉬스트레이트',
 '스코티쉬폴드',
 '스핑크스',
 '싱가푸라',
 '아메리칸 컬',
 '아메리칸숏헤어',
 '아메리칸컬',
 '아비시니안',
 '액죠틱 먼치킨',
 '엑죠틱',
 '제네타 먼치킨',
 '킨카로우',
 '터키쉬앙고라',
 '터키시앙고라',
 '페르시안',
 '페르시안 익스트림',
 '페르시안 친칠라',
 '하이랜드 스트레이트',
 '하이랜드폴드']

In [12]:
BREED_MAP = {
    '먼치': '먼치킨',
    '렉돌':'랙돌',
    '벵갈': '뱅갈',
    '브리티쉬롱헤어':'브리티쉬 롱헤어',
    '브리티쉬먼치킨':'브리티쉬 먼치킨',
    '브리티쉬숏헤어':'브리티쉬 숏헤어',
    '브리티쉿쇼헤어':'브리티쉬 숏헤어',
    '스코티쉬스트레이트':'스코티쉬 스트레이트',
    '스코티쉬폴드':'스코티쉬 폴드',
    '셀커크랙스':'셀커크렉스',
    '아메리칸숏헤어':'아메리칸 숏헤어',
    '아메리칸컬':'아메리칸 컬',
    '액죠틱 먼치킨': '엑죠틱 먼치킨',
    '터키시앙고라':'터키쉬앙고라',
    '하이랜드스트레이트':'하이랜드 스트레이트',
    '하이랜드폴드':'하이랜드 폴드'
}

In [13]:
cats_df['breed'] = (
    cats_df['breed']
    .replace(BREED_MAP)
)

In [14]:
sorted(
    cats_df['breed']
    .dropna()
    .unique()
)

['네바마스커레이드',
 '네벨룽',
 '노르웨이 숲',
 '노르웨이숲',
 '노르웨이숲 먼치킨',
 '데본렉스',
 '랙돌',
 '러시안블루',
 '먼치킨',
 '먼치킨 드월프',
 '먼치킨 래가퍼',
 '먼치킨 램킨',
 '먼치킨 미뉴엣',
 '먼치킨 미뉴엣 (롱)',
 '먼치킨 민스킨',
 '먼치킨 밤비노',
 '먼치킨 엑죠틱',
 '먼치킨 킨카로우',
 '먼치킨 킬트',
 '메인쿤',
 '발리니즈',
 '뱅갈',
 '브리티쉬 롱헤어',
 '브리티쉬 먼처킨',
 '브리티쉬 먼치킨',
 '브리티쉬 숏헤어',
 '샴',
 '샴 먼치킨',
 '셀커크렉스',
 '스코티쉬 스트레이트',
 '스코티쉬 폴드',
 '스핑크스',
 '싱가푸라',
 '아메리칸 숏헤어',
 '아메리칸 컬',
 '아비시니안',
 '엑죠틱',
 '엑죠틱 먼치킨',
 '제네타 먼치킨',
 '킨카로우',
 '터키쉬앙고라',
 '페르시안',
 '페르시안 익스트림',
 '페르시안 친칠라',
 '하이랜드 스트레이트',
 '하이랜드 폴드']

In [15]:
COLOR_MAP = {
    '골드 태비': '골드태비',
    '골드 (ny11)': '골드(ny11)',
    '골드 (ny25)': '골드(ny25)',
    '레드 태비 앤 화이트': '레드태비앤화이트',
    '브라운 로젯': '브라운로젯',
    '블루바이 미티드': '블루바이미티드',
    '화이트 (오드아이)': '화이트(오드아이)',
    '화이트 스킨': '화이트스킨',
    '그래이앤화이트': '그레이앤화이트',
    '세피아 아쿠티': '세피아아구티',
    '세피아 아구티': '세피아아구티',
    '실버클랙식태비': '실버클래식태비',
    '쏘엘': '쏘렐',
    '치즈태앤화이트': '치즈태비앤화이트',
    '크림메커럴태비앤화이트': '크림매커럴태비앤화이트',
}

In [16]:
cats_df['color'] = (
    cats_df['color']
    .replace(COLOR_MAP)
)

In [17]:
sorted(
    cats_df['color']
    .dropna()
    .unique()
)

['골드',
 '골드(ny11)',
 '골드(ny12)',
 '골드(ny25)',
 '골드바이',
 '골드쉐이드',
 '골드칼리코',
 '골드클래식태비앤화이트',
 '골드태비',
 '골드태비바이',
 '골드태비앤화이트',
 '그레이',
 '그레이앤화이트',
 '그레이태비앤화이트',
 '남아',
 '라일락',
 '라일락골드바이',
 '라일락바이',
 '라일락쉐이드앤화이트',
 '라일락앤화이트',
 '라일락태비',
 '라일락태비앤화이트',
 '레드',
 '레드골드',
 '레드바이',
 '레드앤화이트',
 '레드클래식태비',
 '레드태비',
 '레드태비앤화이트',
 '레드포인트',
 '루디',
 '루디, 블루',
 '링스포인트',
 '매커럴바이',
 '매커럴바이, 블루바이',
 '밍크로젯',
 '브라운로젯',
 '브라운마블',
 '브라운멀태비앤화이트',
 '브라운바이',
 '브라운쉐이드앤화이트',
 '브라운스팟',
 '브라운스팟, 실버스팟',
 '브라운앤화이트',
 '브라운클래식태비',
 '브라운태비',
 '브라운태비앤화이트',
 '블랙',
 '블랙/블루바이',
 '블랙바이',
 '블랙브라운앤화이트',
 '블랙스모크',
 '블랙앤화이트',
 '블랙태비앤화이트',
 '블루',
 '블루골드',
 '블루골드(ay12)',
 '블루골드/골드',
 '블루골드바이',
 '블루골드태비',
 '블루골드태비앤화이트',
 '블루링스미티드',
 '블루링스미티드포인트',
 '블루링스바이',
 '블루링스포인트',
 '블루멀앤화이트',
 '블루미티드',
 '블루미티드포인트',
 '블루바이',
 '블루바이미티드',
 '블루쉐이드',
 '블루쉐이드앤화이트',
 '블루태비',
 '블루태비앤화이트',
 '블루토티',
 '블루토티셸',
 '블루토티태비',
 '블루포인트',
 '세피아아구티',
 '솔리드세피아',
 '스노우',
 '스노우로젯',
 '스노우밍크로젯',
 '실버',
 '실버골드쉐이드',
 '실버로젯',
 '실버매커럴태비',
 '실버매커럴태비앤화이트',
 '실버벤',
 '실버브라운스팟',
 '실버쉐이드',
 '실버쉐이드앤화이트',
 '실버쉐이디드',
 '실버스팟',
 '실버앤화이트',
 '실버클래식태비',
 '실버태비',
 '실버태비앤크림패치드',
 '실버태비앤화이트',
 '실버포인트',
 '쏘렐',
 '씰링스미티드',
 '씰링스바이',
 '씰링스포인트',
 '씰미티드',
 '씰바이',
 '씰바이, 블루바이',
 '씰바이미티드',
 '씰포인트',
 '알비노',
 '초코',
 '초코앤화이트',
 '초코태비',
 '초코태비/초코태비앤화이트',
 '초코포인트',
 '치즈앤화이트',
 '치즈태비',
 '치즈태비앤화이트',
 '친칠라',
 '칼리코',
 '칼리코밴',
 '크림',
 '크림/실버앤화이트',
 '크림골드',
 '크림매커럴태비앤화이트',
 '크림바이',
 '크림블루골드',
 '크림블루포인트',
 '크림쉐이드',
 '크림앤화이트',
 '크림태비',
 '크림태비앤화이트',
 '크림패치드실버쉐이드',
 '크림패치드실버태비',
 '크림포인트',
 '토이앤화이트',
 '토티셸',
 '토티앤화이트',
 '파스텔칼리코',
 '폰',
 '핑크골드',
 '핑크골드바이',
 '화이트',
 '화이트(브릿지)',
 '화이트(오드아이)',
 '화이트(크림포인트)',
 '화이트,블랙/레드바이',
 '화이트스킨']

In [18]:
cats_df[
    cats_df['color'] == '남아'
]

,name,breed,detail_url,img_url,gender,age,color,feature,branch
254,보니,브리티쉬 숏헤어,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...,NaN,2개월령,남아,"나 뚠뚜니 아니야,, 얼굴이 넘 빵글해서 구랭,,",마포점

In [19]:
BRANCH_MAP = {
    '잠실 점': '잠실점',
    '왕십리 점': '왕십리점',
}

In [20]:
cats_df['branch'] = (
    cats_df['branch']
    .replace(BRANCH_MAP)
)

In [21]:
sorted(
    cats_df['branch']
    .dropna()
    .unique()
)

['02-2299-0014', '031-657-7024', '마포점', '왕십리', '왕십리점', '잠실점']

In [22]:
cats_df['age_month'] = (
    cats_df['age']
    .apply(normalize_age)
    .astype('Int64')
)

In [23]:
cats_df[
    [
        'age',
        'age_month',
    ]
].head()

    age  age_month
0  2개월령          2
1  2개월령          2
2  2개월령          2
3  2개월령          2
4  2개월령          2

In [24]:
cats_df['age_month'].isnull().sum()

np.int64(8)

In [25]:
cats_df.loc[
    cats_df['age_month'].isnull(),
    'age'
].unique()

<StringArray>
[nan, '남아', '여아', '남아,여아']
Length: 4, dtype: str

In [26]:
FINAL_COLUMNS = [
    'name',
    'breed',
    'gender',
    'age',
    'age_month',
    'color',
    'feature',
    'branch',
    'detail_url',
    'img_url',
]

cats_df = cats_df[
    FINAL_COLUMNS
]

In [27]:
cats_df.head()

,name,breed,gender,age,age_month,color,feature,branch,detail_url,img_url
0,홀앙,브리티쉬 먼치킨,F,2개월령,2,골드바이,왕눈이에 생긴 것 마냥 성격도 순둥이!,왕십리점,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...
1,쨈,브리티쉬 먼치킨,M,2개월령,2,크림바이,오밀조밀 공주 이목구비지만 멋쟁이 왕자다냥!,잠실점,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...
2,리즈,랙돌,F,2개월령,2,블루바이,품에 안기는 순간 인형처럼 스르륵 녹아내리는 원조 봉제인형 냥이,잠실점,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...
3,우디,브리티쉬 숏헤어,M,2개월령,2,블루골드,느긋한 발걸음으로 집사 뒤를 묵묵히 쫓아오는 든든한 친구,왕십리점,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...
4,통깨,노르웨이숲,F,2개월령,2,블루태비앤화이트,NaN,왕십리점,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...

In [28]:
cats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1462 non-null   str
 1   breed       1461 non-null   str
 2   gender      1418 non-null   str
 3   age         1460 non-null   str
 4   age_month   1454 non-null   Int64
 5   color       1460 non-null   str
 6   feature     1457 non-null   str
 7   branch      1417 non-null   str
 8   detail_url  1462 non-null   str
 9   img_url     1462 non-null   str
dtypes: Int64(1), str(9)
memory usage: 115.8 KB

In [29]:
cats_df.isnull().sum()

name           0
breed          1
gender        44
age            2
age_month      8
color          2
feature        5
branch        45
detail_url     0
img_url        0
dtype: int64

In [30]:
missing_rows = cats_df[
    cats_df.isnull().any(axis=1)
]

missing_rows[
    [
        'name',
        'breed',
        'gender',
        'age',
        'age_month',
        'color',
        'feature',
        'branch',
    ]
]

,name,breed,gender,age,age_month,color,feature,branch
4,통깨,노르웨이숲,F,2개월령,2,블루태비앤화이트,NaN,왕십리점
111,티니 & 위니,노르웨이숲,NaN,2개월령,2,브라운태비앤화이트,한날한시 엄마 배에서 같이 태어난 우리는 남매냥!,잠실점
254,보니,브리티쉬 숏헤어,NaN,2개월령,2,남아,"나 뚠뚜니 아니야,, 얼굴이 넘 빵글해서 구랭,,",마포점
390,업로드예정,먼치킨,NaN,NaN,<NA>,NaN,NaN,왕십리점
414,나쵸,브리티쉬 숏헤어,M,2개월령,2,레드바이,NaN,왕십리점
...,...,...,...,...,...,...,...,...
1457,레이,브리티쉬 먼치킨,M,2개월령,2,크림바이,사랑스러운 장난꾸러기 ♥,NaN
1458,테이,브리티쉬 숏헤어,M,2개월령,2,크림태비,차분하고 조용한 사랑둥이 ♥,NaN
1459,릿지,브리티쉬 숏헤어,M,2개월령,2,화이트,호기심 많은 장난꾸러기 애교냥 ♥,NaN
1460,볼링이,브리티쉬 숏헤어,F,2개월령,2,블루바이,장난감을 좋아하는 쾌활한 아꺵이 ♥,NaN
1461,헤미,NaN,NaN,NaN,<NA>,NaN,NaN,NaN

In [31]:
missing_summary = (
    cats_df
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_summary

branch        45
gender        44
age_month      8
feature        5
color          2
age            2
breed          1
name           0
detail_url     0
img_url        0
dtype: int64

In [34]:
REQUIRED_COLUMNS = [
    'name',
    'breed',
    'detail_url',
    'img_url',
]
OPTIONAL_COLUMNS = [
    'gender',
    'age',
    'age_month',
    'color',
    'feature',
    'branch',
]

In [35]:
cats_df[
    cats_df[REQUIRED_COLUMNS]
    .isnull()
    .any(axis=1)
]

,name,breed,gender,age,age_month,color,feature,branch,detail_url,img_url
1461,헤미,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,https://www.dalunacats.com/product/item.php?ca...,https://www.dalunacats.com/product/data/item/1...

In [36]:
cats_df[
    cats_df['breed'].isnull()
][
    [
        'name',
        'detail_url',
        'gender',
        'age',
        'color',
    ]
]

     name                                         detail_url gender  age color
1461   헤미  https://www.dalunacats.com/product/item.php?ca...    NaN  NaN   NaN

In [37]:
cats_df[
    cats_df['breed'].isnull()
][
    ['name', 'detail_url']
]

     name                                         detail_url
1461   헤미  https://www.dalunacats.com/product/item.php?ca...

In [38]:
cats_df[
    cats_df['age_month'].isnull()
][
    ['name', 'age', 'detail_url']
]

       name    age                                         detail_url
390   업로드예정    NaN  https://www.dalunacats.com/product/item.php?ca...
805      하쿠     남아  https://www.dalunacats.com/product/item.php?ca...
977      피버     남아  https://www.dalunacats.com/product/item.php?ca...
1269     찰리     남아  https://www.dalunacats.com/product/item.php?ca...
1415     타로     남아  https://www.dalunacats.com/product/item.php?ca...
1435     흥순     여아  https://www.dalunacats.com/product/item.php?ca...
1443   여름,봄  남아,여아  https://www.dalunacats.com/product/item.php?ca...
1461     헤미    NaN  https://www.dalunacats.com/product/item.php?ca...

In [39]:
INVALID_AGE_VALUES = [
    '남아',
    '여아',
    '남아,여아',
]

cats_df['age'] = (
    cats_df['age']
    .replace(INVALID_AGE_VALUES, pd.NA)
)

In [40]:
cats_df['age_month'] = (
    cats_df['age']
    .apply(normalize_age)
    .astype('Int64')
)

In [41]:
cats_df[
    cats_df['age_month'].isnull()
][
    ['name', 'age', 'age_month']
]

       name  age  age_month
390   업로드예정  NaN       <NA>
805      하쿠  NaN       <NA>
977      피버  NaN       <NA>
1269     찰리  NaN       <NA>
1415     타로  NaN       <NA>
1435     흥순  NaN       <NA>
1443   여름,봄  NaN       <NA>
1461     헤미  NaN       <NA>

In [42]:
cats_df[
    cats_df['gender'].isnull()
][
    [
        'name',
        'age',
        'color',
        'feature',
        'branch',
        'detail_url',
    ]
]

,name,age,color,feature,branch,detail_url
111,티니 & 위니,2개월령,브라운태비앤화이트,한날한시 엄마 배에서 같이 태어난 우리는 남매냥!,잠실점,https://www.dalunacats.com/product/item.php?ca...
254,보니,2개월령,남아,"나 뚠뚜니 아니야,, 얼굴이 넘 빵글해서 구랭,,",마포점,https://www.dalunacats.com/product/item.php?ca...
390,업로드예정,NaN,NaN,NaN,왕십리점,https://www.dalunacats.com/product/item.php?ca...
454,"단이, 밤이",2개월령,골드,터질 것 같은 볼 뚠뚜니 남매냥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
474,"티모, 토모",2개월령,블루바이,찰싹 붙어 안 떨어지는 사이 좋은 형제냥이들,잠실점,https://www.dalunacats.com/product/item.php?ca...
535,"자두,레몬,체리,애플",2개월령,골드,냥꼬발랄 사둥이들 ~,잠실점,https://www.dalunacats.com/product/item.php?ca...
537,"유자,자몽,살구,감귤",2개월령,골드,귀욤뽀짝 ! 짧은 코 ! 언제나 집사 옆을 지켜요💛,마포점,https://www.dalunacats.com/product/item.php?ca...
568,모리,2개월령,블루골드,사람 뒤만 졸졸~~ 사람이 너무 좋아~,왕십리점,https://www.dalunacats.com/product/item.php?ca...
588,진저,2개월령,골드,동그리동동 ! 사진보다 실물이 훨배 이뿌다구용 ! 😍🧡,왕십리점,https://www.dalunacats.com/product/item.php?ca...
799,두유,2개월령,크림,귀염발사 사랑둥이🥰,왕십리점,https://www.dalunacats.com/product/item.php?ca...
805,하쿠,NaN,실버태비,멋짐 뿜뿜 모델냥이 😎초코젤리 보고가세유! 🍫,마포점,https://www.dalunacats.com/product/item.php?ca...
811,하로&하리,2개월령,블루,활발한 애교냥이들😻😸,왕십리점,https://www.dalunacats.com/product/item.php?ca...
815,아무&아매,2개월령,실버클래식태비,사람만 보면 다가가는 개냥이들😻,왕십리점,https://www.dalunacats.com/product/item.php?ca...
818,미노&미누,2개월령,블루,애교만땅 까불냥이들😆,왕십리점,https://www.dalunacats.com/product/item.php?ca...
923,호두&호량,2개월령,골드,쓰다듬어주는걸 좋아하는 남매냥이다옹(ง˙∇˙)ว,왕십리점,https://www.dalunacats.com/product/item.php?ca...
939,루크&치앙,2개월령,"루디, 블루",낯가림 없는 귀요미 남매다냥 (*･▽･*),왕십리점,https://www.dalunacats.com/product/item.php?ca...
977,피버,NaN,블루바이,"골골송이 그칠줄을 몰라효,,😻",왕십리점,https://www.dalunacats.com/product/item.php?ca...
1008,삼둥이들,2개월령,골드,호기심 가득 사람손을 좋아하는 개냥이에오♥ㅁ♥,마포점,https://www.dalunacats.com/product/item.php?ca...
1069,래리&도리,2개월령,블루바이,장난꾸러기 뽀솜이들♥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1076,오밀&조밀,2개월령,블루링스포인트,통통한 뱃살을 자랑하는 귀요미들💞,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1089,시나/모나,2개월령,세피아아구티,"세상에서 제일 작은냥이! 엄지공주,왕자냥😊",마포점,https://www.dalunacats.com/product/item.php?ca...
1124,호랭 삼둥,2개월령,골드,귀여운 토실토실 아가 호랭이들 🐱🐯,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1204,"달봉,달희",1개월령,골드,달루 아빠 붕어빵이들♡,마포점,https://www.dalunacats.com/product/item.php?ca...
1258,"알콩,달콩",2개월령,블루,사이좋은 꾹꾹이 전도사들,NaN,https://www.dalunacats.com/product/item.php?ca...
1269,찰리,NaN,골드,터질듯한 볼살과 궁댕이로 여심을 녹이는 황금부자,NaN,https://www.dalunacats.com/product/item.php?ca...
1281,"이든,르네",2개월령,블랙/블루바이,안기면 골골송 자동재생 귀요미들,NaN,https://www.dalunacats.com/product/item.php?ca...
1286,"캐롤,돌프",2개월령,블루,애교많고 귀여운 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1294,"톰,제리",2개월령,친칠라,꽃단장 전문 그루밍 전도사들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1300,"초코,라떼",2개월령,씰포인트,아웅당웅 사이좋은 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1339,"뚜순,뚜뚜",2개월령,블루,차분하고 조용한 밥도둑들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1353,"코코,코아",2개월령,브라운태비앤화이트,우다다를 좋아하는 운동광냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1366,"라희,라라",2개월령,씰포인트,사랑스런 장난꾸러기 아깽남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1376,"랄라,블라",2개월령,실버태비,똥고발랄 애교많은 아깽남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1377,"레옹,틸다",2개월령,씰포인트,사랑둥이 개냥이남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1381,"봉봉,도담",2개월령,블루,애교만점 사랑스러운 개냥이 남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1388,"칠리,살사",2개월령,친칠라,순둥한 복실이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1409,레인보우,2개월령,"화이트,블랙/레드바이",사람을 너무너무 좋아하는 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1414,"동이,여비",2개월령,블루,똥꼬발랄 개구쟁이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1415,타로,NaN,블루바이미티드,안으면 착 안기는 봉제인형냥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1430,"페리,페라,페로",2개월령,화이트,애교폭발 귀여운 광냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1433,"써니,하니",2개월령,블랙/블루바이,쾌활 활발 말괄냥이,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1435,흥순,NaN,토티앤화이트,귀여운 아깽냥이,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1443,"여름,봄",NaN,크림/실버앤화이트,사고뭉치 귀요미들,NaN,https://www.dalunacats.com/product/item.php?ca...
1461,헤미,NaN,NaN,NaN,NaN,https://www.dalunacats.com/product/item.php?ca...

In [43]:
for column in [
    'age',
    'color',
    'feature',
    'branch',
]:
    result = cats_df[
        cats_df[column]
        .astype(str)
        .str.contains('남아|여아', na=False)
    ]

    print(column, len(result))

age 0
color 1
feature 0
branch 0

In [44]:
cats_df[
    cats_df['color']
    .astype(str)
    .str.contains('남아|여아', na=False)
][
    [
        'name',
        'gender',
        'age',
        'color',
        'branch',
        'detail_url',
    ]
]

,name,gender,age,color,branch,detail_url
254,보니,NaN,2개월령,남아,마포점,https://www.dalunacats.com/product/item.php?ca...

In [45]:
mask = (
    cats_df['gender'].isnull()
    & cats_df['color'].isin(['남아', '여아'])
)

cats_df.loc[
    mask,
    'gender'
] = (
    cats_df.loc[
        mask,
        'color'
    ]
    .map({
        '남아': 'M',
        '여아': 'F',
    })
)

cats_df.loc[
    mask,
    'color'
] = pd.NA

In [46]:
print(
    'gender 결측:',
    cats_df['gender'].isnull().sum()
)

print(
    'color 결측:',
    cats_df['color'].isnull().sum()
)

gender 결측: 43
color 결측: 3

In [47]:
cats_df[
    cats_df['gender'].isnull()
][
    [
        'name',
        'age',
        'color',
        'feature',
        'branch',
        'detail_url',
    ]
]

,name,age,color,feature,branch,detail_url
111,티니 & 위니,2개월령,브라운태비앤화이트,한날한시 엄마 배에서 같이 태어난 우리는 남매냥!,잠실점,https://www.dalunacats.com/product/item.php?ca...
390,업로드예정,NaN,NaN,NaN,왕십리점,https://www.dalunacats.com/product/item.php?ca...
454,"단이, 밤이",2개월령,골드,터질 것 같은 볼 뚠뚜니 남매냥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
474,"티모, 토모",2개월령,블루바이,찰싹 붙어 안 떨어지는 사이 좋은 형제냥이들,잠실점,https://www.dalunacats.com/product/item.php?ca...
535,"자두,레몬,체리,애플",2개월령,골드,냥꼬발랄 사둥이들 ~,잠실점,https://www.dalunacats.com/product/item.php?ca...
537,"유자,자몽,살구,감귤",2개월령,골드,귀욤뽀짝 ! 짧은 코 ! 언제나 집사 옆을 지켜요💛,마포점,https://www.dalunacats.com/product/item.php?ca...
568,모리,2개월령,블루골드,사람 뒤만 졸졸~~ 사람이 너무 좋아~,왕십리점,https://www.dalunacats.com/product/item.php?ca...
588,진저,2개월령,골드,동그리동동 ! 사진보다 실물이 훨배 이뿌다구용 ! 😍🧡,왕십리점,https://www.dalunacats.com/product/item.php?ca...
799,두유,2개월령,크림,귀염발사 사랑둥이🥰,왕십리점,https://www.dalunacats.com/product/item.php?ca...
805,하쿠,NaN,실버태비,멋짐 뿜뿜 모델냥이 😎초코젤리 보고가세유! 🍫,마포점,https://www.dalunacats.com/product/item.php?ca...
811,하로&하리,2개월령,블루,활발한 애교냥이들😻😸,왕십리점,https://www.dalunacats.com/product/item.php?ca...
815,아무&아매,2개월령,실버클래식태비,사람만 보면 다가가는 개냥이들😻,왕십리점,https://www.dalunacats.com/product/item.php?ca...
818,미노&미누,2개월령,블루,애교만땅 까불냥이들😆,왕십리점,https://www.dalunacats.com/product/item.php?ca...
923,호두&호량,2개월령,골드,쓰다듬어주는걸 좋아하는 남매냥이다옹(ง˙∇˙)ว,왕십리점,https://www.dalunacats.com/product/item.php?ca...
939,루크&치앙,2개월령,"루디, 블루",낯가림 없는 귀요미 남매다냥 (*･▽･*),왕십리점,https://www.dalunacats.com/product/item.php?ca...
977,피버,NaN,블루바이,"골골송이 그칠줄을 몰라효,,😻",왕십리점,https://www.dalunacats.com/product/item.php?ca...
1008,삼둥이들,2개월령,골드,호기심 가득 사람손을 좋아하는 개냥이에오♥ㅁ♥,마포점,https://www.dalunacats.com/product/item.php?ca...
1069,래리&도리,2개월령,블루바이,장난꾸러기 뽀솜이들♥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1076,오밀&조밀,2개월령,블루링스포인트,통통한 뱃살을 자랑하는 귀요미들💞,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1089,시나/모나,2개월령,세피아아구티,"세상에서 제일 작은냥이! 엄지공주,왕자냥😊",마포점,https://www.dalunacats.com/product/item.php?ca...
1124,호랭 삼둥,2개월령,골드,귀여운 토실토실 아가 호랭이들 🐱🐯,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1204,"달봉,달희",1개월령,골드,달루 아빠 붕어빵이들♡,마포점,https://www.dalunacats.com/product/item.php?ca...
1258,"알콩,달콩",2개월령,블루,사이좋은 꾹꾹이 전도사들,NaN,https://www.dalunacats.com/product/item.php?ca...
1269,찰리,NaN,골드,터질듯한 볼살과 궁댕이로 여심을 녹이는 황금부자,NaN,https://www.dalunacats.com/product/item.php?ca...
1281,"이든,르네",2개월령,블랙/블루바이,안기면 골골송 자동재생 귀요미들,NaN,https://www.dalunacats.com/product/item.php?ca...
1286,"캐롤,돌프",2개월령,블루,애교많고 귀여운 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1294,"톰,제리",2개월령,친칠라,꽃단장 전문 그루밍 전도사들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1300,"초코,라떼",2개월령,씰포인트,아웅당웅 사이좋은 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1339,"뚜순,뚜뚜",2개월령,블루,차분하고 조용한 밥도둑들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1353,"코코,코아",2개월령,브라운태비앤화이트,우다다를 좋아하는 운동광냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1366,"라희,라라",2개월령,씰포인트,사랑스런 장난꾸러기 아깽남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1376,"랄라,블라",2개월령,실버태비,똥고발랄 애교많은 아깽남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1377,"레옹,틸다",2개월령,씰포인트,사랑둥이 개냥이남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1381,"봉봉,도담",2개월령,블루,애교만점 사랑스러운 개냥이 남매,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1388,"칠리,살사",2개월령,친칠라,순둥한 복실이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1409,레인보우,2개월령,"화이트,블랙/레드바이",사람을 너무너무 좋아하는 개냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1414,"동이,여비",2개월령,블루,똥꼬발랄 개구쟁이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1415,타로,NaN,블루바이미티드,안으면 착 안기는 봉제인형냥,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1430,"페리,페라,페로",2개월령,화이트,애교폭발 귀여운 광냥이들,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1433,"써니,하니",2개월령,블랙/블루바이,쾌활 활발 말괄냥이,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1435,흥순,NaN,토티앤화이트,귀여운 아깽냥이,왕십리점,https://www.dalunacats.com/product/item.php?ca...
1443,"여름,봄",NaN,크림/실버앤화이트,사고뭉치 귀요미들,NaN,https://www.dalunacats.com/product/item.php?ca...
1461,헤미,NaN,NaN,NaN,NaN,https://www.dalunacats.com/product/item.php?ca...

In [48]:
cats_df[
    cats_df['breed'].isnull()
][
    [
        'name',
        'gender',
        'age',
        'color',
        'branch',
        'detail_url',
    ]
]

,name,gender,age,color,branch,detail_url
1461,헤미,NaN,NaN,NaN,NaN,https://www.dalunacats.com/product/item.php?ca...

In [49]:
cats_df = cats_df[
    cats_df['breed'].notnull()
].reset_index(drop=True)

In [50]:
cats_df.isnull().sum()

name           0
breed          0
gender        42
age            7
age_month      7
color          2
feature        4
branch        44
detail_url     0
img_url        0
dtype: int64

In [51]:
print('gender')
print(cats_df['gender'].value_counts(dropna=False))

print('\nage_month')
print(cats_df['age_month'].value_counts(dropna=False).sort_index())

print('\nbranch')
print(cats_df['branch'].value_counts(dropna=False))

gender
gender
M      915
F      504
NaN     42
Name: count, dtype: int64

age_month
age_month
1          1
2       1440
3         10
4          1
5          1
6          1
<NA>       7
Name: count, dtype: Int64

branch
branch
왕십리점            822
마포점             453
잠실점             138
NaN              44
왕십리               2
031-657-7024      1
02-2299-0014      1
Name: count, dtype: int64

In [52]:
from datetime import datetime

today = datetime.now().strftime('%Y%m%d')

CLEANED_CSV_PATH = (
    PROCESSED_DIR
    / f'site_01_cleaned_cats_{today}.csv'
)

cats_df.to_csv(
    CLEANED_CSV_PATH,
    index=False,
    encoding='utf-8-sig',
)

print(CLEANED_CSV_PATH)

D:\anaconda\data\processed\site_01_cleaned_cats_20260829.csv

In [53]:
saved_df = pd.read_csv(
    CLEANED_CSV_PATH
)

print(saved_df.shape)
print(saved_df.columns.tolist())

(1461, 10)
['name', 'breed', 'gender', 'age', 'age_month', 'color', 'feature', 'branch', 'detail_url', 'img_url']